### ISSUE TITLE
subsets to SARC Files

### ISSUE THREAD

**Issue by guoxuxu** [NLPrinceton/SARC#2]
Hi, ~~ Thanks a million if you can help me clarify a data source question!
I visited the link to SARC Files. There are only two folders - main and pol for sarcasm evaluation, right?

However, I read two papers [1] [2], they all claimed they used two subsets: /r/movies and /r/technology from your SARC dataset. [1] claimed they used 8188 samples from /r/movies and 22510 samples from /r/technology. [2] claimed they used said they used 15019 samples from r/movies and 13485 samples from r/technology. [2] gave a link to SARC-2.0.

I checked that in the SARC-2.0 main folder, there are 
train-balanced r/movies=1414, train-unbalanced r/movies=121595 
test-balanced r/movies=364, test-unbalanced r/movies=27930
train-balanced r/technology=1652, train-unbalanced r/technology=73641 
test-balanced r/technology=408, test-unbalanced r/technology=20104

It's impossible to get a balanced dataset for both [1] and [2], right?.. the sarc samples are very few compared with non-sarc samples...

could you help me check if there is any way for the two papers to get such data?
Thanks a million! This confused me quite a lot.

[1] https://www.aclweb.org/anthology/P18-1093.pdf
[2] https://dl.acm.org/doi/pdf/10.1145/3308558.3313735

**Comment by mkhodak** [comment]
Hello. Since they didn't use any of our partitions of SARC 2.0 directly, the best way to find out how these papers obtained their data is by asking the authors themselves. I can only speculate as to what they did; for example, they might have used the 'raw' partition of SARC 2.0, which has many more examples.
